_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
    DEPTH: 101x

DATASETS:
  NAMES: ("AICUP",)
  TESTS: ("AICUP",)

DATALOADER:
    NUM_WORKERS: 2

SOLVER:
  BIAS_LR_FACTOR: 1.

  IMS_PER_BATCH: 256
  MAX_EPOCH: 60
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 1

CUDNN_BENCHMARK: True

OUTPUT_DIR: logs/AICUP/sbs_S101
